# Generated by Django 5.1.6 on 2025-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('heard_about', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('mattress_type', models.CharField(blank=True, max_length=50, null=True)),
                ('comfort_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('quality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('support_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_location', models.CharField(blank=True, max_length=50, null=True)),
                ('shopping_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('price_satisfaction', models.CharField(blank=True, max_length=50, null=True)),
                ('product_details', models.CharField(blank=True, max_length=50, null=True)),
                ('likes', models.TextField(blank=True, null=True)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
