# Generated by Django 5.1.6 on 2025-02-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_surveyresponse_heard_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='comfort_rating',
            new_name='comfortRating',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='mattress_type',
            new_name='mattressType',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='price_satisfaction',
            new_name='priceSatisfaction',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='product_details',
            new_name='productDetails',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='purchase_location',
            new_name='purchaseLocation',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='quality_rating',
            new_name='qualityRating',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='shopping_experience',
            new_name='shoppingExperience',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='support_rating',
            new_name='supportRating',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='usage_duration',
            new_name='usageDuration',
        ),
    ]
