# Generated by Django 5.1.6 on 2025-02-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
