# Generated by Django 5.1.6 on 2025-02-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_surveyresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={},
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='comfortRating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='qualityRating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='recommendation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='supportRating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
