# Generated by Django 5.1.6 on 2025-02-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0008_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='groups',
            field=models.ManyToManyField(related_name='admin_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='admin_user_permissions', to='auth.permission'),
        ),
    ]
