# Generated by Django 5.1.6 on 2025-02-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_adminuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
